# basic options
title: Welcome World
author: Thusha S
email: thusha.siva96@gmail.com
description: Test Site
facebook_username: thusha.siva
github_username: ThushaSiva

# Build settings
markdown: kramdown
theme: minima
